describe("Testing the Learn More Page", () => {
    beforeEach(() => {
        cy.viewport(1536, 960);
    });

    it("Checking the Frequently Asked Question section", () => {
        cy.visit("/");
        cy.contains("Learn More").click();

        //   Check the path (/learnmore)
        cy.url().should("include", "learnmore");

        //   Check whether 6 questions exist
        cy.get(".faq-question").should("have.length", 6);

        //   Check whether 6 answers exist
        cy.get(".faq-answer").should("have.length", 6);

        //   Check if all the 6 questions whether they exist
        cy.contains("What is Text Insights?").click();
        cy.contains("How does Text Insights summarise text?").click();
        cy.contains("What is sentiment analysis, and why is it important?").click();
        cy.contains("How accurate is Text Insights' sentiment analysis using BERT?").click();
        cy.contains("Can Text Insights summarise any type of text?").click();
        cy.contains("What is the maximum length of the summary generated by Text Insights?").click();

        //   Check if q1's answer exists
        cy.get(".faq-answer").should("contain", "Text Insights is an online text summariser");

        //   Check if q2's answer exists
        cy.get(".faq-answer").should("contain", "Text Insights uses the powerful BERT");
        //   Check if q3's answer exists
        cy.get(".faq-answer").should("contain", "Sentiment analysis is the process of determining the emotional tone");
        //   Check if q4's answer exists
        cy.get(".faq-answer").should("contain", "Text Insights utilises BERT-based sentiment analysis models");
        //   Check if q5's answer exists
        cy.get(".faq-answer").should("contain", "Text Insights can summarise a wide range of text types");
        //   Check if q6's answer exists
        cy.get(".faq-answer").should("contain", "The maximum summary length generated by Text Insights is set at 400");
    });

    it("Checking the Learning Material (NLP) Material Summary section", () => {
        cy.visit("/");
        cy.contains("Learn More").click();

        //   Check the path (/learnmore)
        cy.url().should("include", "learnmore");

        cy.contains("What dataset was Text Insights trained on?").click();
        cy.get("#0").should("contain", "BERT");

        cy.contains("What dataset was Text Insights trained on?").click();
        cy.contains("How does BERT work?").click();
        cy.get("#1").should("contain", "BERT");

        cy.contains("How does BERT work?").click();
    });
});
