describe("Sentiment Analysis Test", () => {
  const randomParagraphs = [
    "As the sun dipped below the horizon, the city's skyline was bathed in hues of orange and pink. The transition from day to night brought a sense of calm to the bustling metropolis. It was a moment to pause and appreciate the beauty of twilight. As the sun dipped below the horizon, the city's skyline was bathed in hues of orange and pink. The transition from day to night brought a sense of calm to the bustling metropolis. It was a moment to pause and appreciate the beauty of twilight. The transition from day to night brought a sense of calm to the bustling metropolis. It was a moment to pause and appreciate the beauty of twilight. As the sun dipped below the horizon, the city's skyline was bathed in hues of orange and pink. The transition from day to night brought a sense of calm to the bustling metropolis. It was a moment to pause and appreciate the beauty of twilight.",
    "Baldwin IV of Jerusalem, also known as Baldwin the Leper, reigned as the King of Jerusalem from 1174 to 1185. He was born in 1161 and was the son of Amalric I of Jerusalem and Agnes of Courtenay. Baldwin IV is a significant figure in the history of the Kingdom of Jerusalem during the time of the Crusades. Baldwin IV's reign was marked by the challenges he faced due to his health. He was afflicted with leprosy, a chronic, debilitating disease. Despite his illness, Baldwin IV became king at a very young age, and his mother, Agnes, served as his regent during his early years. As he grew older, he began to assert his independence and rule in his own right. During his reign, the kingdom faced external threats from Muslim forces, most notably the famous Muslim military leader Saladin (Salah ad-Din). Despite his illness, Baldwin IV displayed remarkable courage and determination in defending the kingdom against Saladin's advances. One of the notable battles during this period was the Battle of Montgisard in 1177, where Baldwin IV, along with his general Balian of Ibelin, achieved a remarkable victory against Saladin's larger forces.",
    "NASA, which stands for the National Aeronautics and Space Administration, is the United States government agency responsible for the nation's civilian space program and for aeronautics and aerospace research. Established on July 29, 1958, NASA has played a pivotal role in advancing human understanding of space, Earth, and the universe. Here are some key aspects of NASA: Space Exploration: NASA is renowned for its exploration of space. It has sent numerous missions to explore our solar system and beyond. Notable achievements include landing astronauts on the Moon during the Apollo program and sending robotic missions to study Mars, Jupiter, Saturn, and Pluto.Human Spaceflight: NASA conducts human spaceflight missions and operates the International Space Station (ISS) in collaboration with multiple international partners. It has launched space shuttles, and it is currently developing the Artemis program with the goal of returning humans to the Moon and ultimately sending astronauts to Mars. Robotic Missions: NASA has sent a multitude of robotic spacecraft to explore other celestial bodies. These missions have included the Mars Rovers (Spirit, Opportunity, Curiosity, and Perseverance), the Voyager spacecraft, the Hubble Space Telescope, and the New Horizons mission to Pluto. Astronomy and Space Research: NASA plays a significant role in space-based astronomy and research. It operates the Hubble Space Telescope and the James Webb Space Telescope, both of which provide critical insights into the universe. NASA conducts research on Earth science, astrophysics, heliophysics, and planetary science.",
    "I am ChatGPT, an AI language model developed by OpenAI, based on the GPT-3.5 architecture. I am a computer program designed to understand and generate human-like text based on the input I receive. Here are some key points about me: Knowledge Base: My responses are generated based on a large dataset of text from the internet, books, articles, and more, up until my knowledge cutoff date in September 2021. I don't have real-time access to the internet or current events beyond that date. Natural Language Processing: I am capable of understanding and generating human language text. I can answer questions, provide explanations, assist with writing, and engage in text-based conversations on a wide range of topics. No Personal Identity: I am not a human, and I don't possess personal experiences, emotions, or consciousness. I'm a tool designed to provide information and generate text based on the input and prompts I receive. Impartiality: I don't have personal opinions or biases. My responses are based on patterns in the text data I was trained on, and I aim to provide objective and balanced information.",
    "The France Catacombs, commonly referred to as the Paris Catacombs (Les Catacombes de Paris), are an extensive underground ossuary located beneath the streets of Paris, France. The catacombs are a network of tunnels and chambers that house the remains of millions of people, and they have a fascinating and somewhat eerie history. Here are some key facts about the Paris Catacombs: Historical Background: The history of the Paris Catacombs dates back to the late 18th century. Prior to their establishment, Paris faced issues with overcrowded cemeteries, unsanitary conditions, and the spread of disease due to the improper disposal of human remains. Creation: In the late 18th century, city officials decided to address these issues by relocating the remains from several overpopulated cemeteries to abandoned underground quarries. The process of transferring remains began in 1786. Mass Burial Site: Over a period of several years, the remains of approximately six million people were transferred to the catacombs. These remains include skeletons and bones. Organization: The catacombs are organized into numerous chambers and tunnels, and the bones are often neatly arranged in artistic patterns and designs. Inscriptions and plaques throughout the catacombs provide information about the origin of the transferred remains. Tourist Attraction: Today, the Paris Catacombs are a popular tourist attraction, offering visitors the opportunity to explore a small portion of the vast underground network. The tour allows visitors to see the carefully arranged remains, as well as to learn about the history and significance of the catacombs. Mysterious and Atmospheric: The catacombs are known for their mysterious and somewhat eerie ambiance. The underground tunnels and chambers create an atmosphere that has intrigued both tourists and explorers. Urban Legends: Over the years, the catacombs have been the subject of urban legends and stories about secret passageways, hidden treasures, and even illicit activities. However, most of these claims are not based in reality. Conservation and Preservation: Due to their historical and cultural significance, efforts are made to preserve the catacombs and ensure the safety of visitors. Only a small portion of the catacombs is open to the public, and unauthorized access to other parts is illegal and dangerous.",
    "NVIDIA Corporation, commonly known as NVIDIA, is a multinational technology company renowned for its contributions to the field of graphics processing units (GPUs), as well as its involvement in artificial intelligence (AI) and other advanced computing technologies. Here are some key points about NVIDIA: Founding and History: NVIDIA was founded in 1993 by Jensen Huang, Chris Malachowsky, and Chris Hsieh. The company's headquarters is in Santa Clara, California. Graphics Processing Units (GPUs): NVIDIA is most well-known for its GPUs, which are semiconductor devices used to accelerate the rendering of graphics and images in computers, gaming consoles, and other electronic devices. The company's GeForce series of GPUs is popular among gamers, while its Quadro and Tesla series are used in professional and scientific applications. Graphics Technologies: NVIDIA has made significant contributions to graphics technologies, including the development of advanced rendering techniques and features, such as ray tracing, which greatly enhances the realism of computer-generated graphics. Gaming: NVIDIA's GeForce graphics cards are widely used in the gaming industry, providing high-quality graphics performance for gaming enthusiasts. The company also develops software and tools for game developers. Artificial Intelligence: NVIDIA has played a crucial role in the development and popularization of AI and deep learning technologies. Its GPUs are well-suited for training and running neural networks. The CUDA platform and cuDNN library are used in AI research and development.",
    "The Fast & Furious film franchise, known for its high-octane action sequences, fast cars, and daring stunts, is a matter of personal preference when it comes to whether it is too much. Whether a film is enjoyable or overwhelming depends on individual taste in movies. The Fast & Furious franchise has garnered a large and dedicated fan base over the years, thanks to its combination of action, spectacle, and a diverse ensemble cast. It is known for pushing the boundaries of physics and realism, with increasingly extravagant stunts and action scenes. Some viewers appreciate this aspect of the films, finding them thrilling and entertaining. On the other hand, some critics and viewers may argue that the franchise has become too focused on spectacle and less on character development or a cohesive storyline. They might find the extreme action sequences and emphasis on over-the-top stunts to be excessive and detracting from the storytelling.",
    "Australia is home to a diverse range of snake species, some of which are highly venomous. Here are some key points about snakes in Australia: Diversity: Australia boasts more than 170 species of land snakes, making it home to some of the world's most venomous snakes. These snakes are found in a variety of habitats, ranging from forests and deserts to grasslands and coastal regions. Venomous Snakes: Australia is known for its venomous snakes, many of which belong to the family Elapidae. Some of the most infamous venomous snakes in Australia include the Inland Taipan, Coastal Taipan, Eastern Brown Snake, Western Brown Snake, and the Tiger Snake. Elapids: The elapid family includes the highly venomous snakes with fixed front fangs. They are responsible for the majority of snakebite-related deaths in Australia. Antivenom is available for the treatment of bites from many of these species.",
    "The best time to go to sleep can vary from person to person and is influenced by several factors, including individual sleep needs, lifestyle, and circadian rhythms. Circadian rhythms are your body's natural internal clock, which regulates the sleep-wake cycle. Here are some considerations for finding the ideal bedtime: Recommended Amount of Sleep: The amount of sleep needed varies by age. On average, adults require 7-9 hours of sleep per night. It's essential to get enough sleep to ensure optimal physical and mental well-being. Circadian Rhythms: Most people have a natural circadian rhythm that aligns with the day-night cycle. Going to bed and waking up at roughly the same time each day can help synchronize your body's internal clock with external cues, making it easier to fall asleep and wake up.E arly Birds vs. Night Owls: People tend to have different chronotypes, which determine their natural preference for sleep timing.",
    "Octopuses have three hearts. Two pump blood to the gills, while the third pumps it to the rest of the body. Additionally, their blue blood is copper-based, which makes it blue rather than red like human blood, and it's exceptionally efficient at transporting oxygen, even in low-oxygen environments. Octopuses are fascinating creatures with many unique adaptations, and their three hearts are just one example of their remarkable biology. Octopuses have three hearts. Two pump blood to the gills, while the third pumps it to the rest of the body. Additionally, their blue blood is copper-based, which makes it blue rather than red like human blood, and it's exceptionally efficient at transporting oxygen, even in low-oxygen environments. Octopuses are fascinating creatures with many unique adaptations, and their three hearts are just one example of their remarkable biology.",
    "Kyriakos S. Pittakis (also Pittakys; Greek: Κυριακός Σ. Πιττάκης; 1798. 4 November [O.S. 23 October] 1863)[a] was a Greek archaeologist. He was the first Greek to serve as Ephor General of Antiquities, the head of the Greek Archaeological Service, in which capacity he carried out the conservation and restoration of several monuments on the Acropolis of Athens. He has been described as a dominant figure in Greek archaeology for 27 years, and as one of the most important epigraphers of the nineteenth century.[4] Pittakis was largely self-taught as an archaeologist, and one of the few native Greeks active in the field during the late Ottoman period and the early years of the Kingdom of Greece. He played an influential role in the early years of the Greek Archaeological Service and was a founding member of the Archaeological Society of Athens, a private body that undertook the excavation, conservation and publication of archaeological finds. He was responsible for much of the early excavation and restoration of the Acropolis, including attempts to restore the Erechtheion, the Parthenon, the Temple of Athena Nike and the Propylaia. As ephor of the Central Public Museum for Antiquities from 1836, and later as Ephor General, he was largely responsible for the conservation and protection of many of the monuments and artefacts then known from Ancient Greece.",
    "Pardies was born in Pau, France, the son of an advisor at the local assembly. He entered the Society of Jesus on 17 November 1652 and for a time taught classical literature; during this period he composed a number of short Latin works, in prose and verse. After his ordination, he taught philosophy and mathematics at the Collège de Clermont in Paris, which would eventually become the Lycée Louis-le-Grand. His earliest scientific work is the Horologium Thaumanticum Duplex (Paris, 1662), in which is described an instrument he had invented for constructing various kinds of sundials. Three years later appeared his Dissertatio de Motu et Natura Cometarum, published separately in Latin and in French (Bordeaux, 1665). His La Statique (Paris, 1673) argued that Galileo's theory was not exact. This, along with Discours du mouvement local (Paris, 1670), and the manuscript Traité complet d'Optique, in which he followed the undulatory theory of light (which identifies it as a harmonic vibration), form part of a general work on physics which he had planned. Traité complet d'Optique had been studied by Pierre Ango (1640-1694) a confrere of Pardies for his Book L`Optique[2] which he published in 1682 after Pardies early death. The Manuscript has also been mentioned by Christiaan Huygens in his Treatise on Light. Huygens himself mentioned in 1668 that it has been Pardies' Theory that the speed of light is finite.[3]",
    "The Bruins entered the 1974-75 season coming off a loss in the Final Four of the 1974 NCAA tournament, which ended a streak of seven consecutive national championships. The team had won titles in nine of the previous 11 seasons, all of which were earned under head coach John Wooden, who was in his 27th season with UCLA.[2] Following the team's defeat against North Carolina State, multiple Bruins players were selected in the 1974 NBA draft, including Bill Walton—who had been chosen as the national player of the year—and Jamaal Wilkes.[3] Senior forward Dave Meyers led the 1974-75 Bruins in scoring with an average of 18.3 points per game, and had a team-high 7.9 rebounds per game. Richard Washington, a sophomore center, added 15.9 points and 7.8 rebounds per game.[4] Sophomore forward Marques Johnson and senior center Pete Trgovich also had double-figure scoring averages, with 11.6 and 10.2 points per game respectively. Other regulars in the Bruins' roster included center Ralph Drollinger and guard Andre McCarter.[4]",
    "The Lamborghini Aventador SuperVeloce LP 750-4 was announced at the 2015 Geneva Motor Show. It featured an upgraded powertrain, with maximum power output increased to 750 PS (552 kW; 740 hp) from the standard coupé's 700 PS (515 kW; 690 hp). Combined with a weight reduction of 50 kg (110 lb) from increased usage of carbon fibre both inside and outside the car, the SV LP 750-4 has a power-to-weight ratio of 1 hp to 2 kg. The car also features improved aerodynamics, with downforce increased by 180% as compared to the standard Aventador coupé. Notable aerodynamic upgrades are a revised front splitter and a rear diffuser, along with a fixed CFRP rear wing. The car's driving dynamics have also been upgraded, featuring new enhanced electronic steering for superior maneuverability at high speeds, magnetic push-rod suspension for superior handling, and chassis improvements to increase rigidity. Overall, the SV LP 750-4's 0-100 km/h (0-62 mph) acceleration time is decreased from 2.9 seconds to 2.8 seconds, with the theoretical top speed still somewhere in excess of 350 km/h (217 mph). Delivery of the car began in the second quarter of 2015 with production limited to 600 units.[35][36] Road & Track recorded a 0-241 km/h (0-150 mph) time of 12.8 seconds, a 0-322 km/h (0-200 mph) time of 33.5 seconds, and a 0-1/4 mile (402 m) trap speed of 227.4 km/h (141.3 mph) in the March 2016 0-322 km/h (0-200 mph) shootout.[37]",
    "The Giza pyramid complex (also called the Giza necropolis) in Egypt is home to the Great Pyramid, the Pyramid of Khafre, and the Pyramid of Menkaure, along with their associated pyramid complexes and the Great Sphinx. All were built during the Fourth Dynasty of the Old Kingdom of ancient Egypt, between 2600 and 2500 BC. The site also includes several temples and cemeteries and the remains of a workers' village. The site is at the edges of the Western Desert, approximately 9 kilometres (5.6 mi) west of the Nile River in the city of Giza, and about 13 kilometres (8 mi) southwest of the city centre of Cairo. It forms the northernmost part of the 16,000-hectare (40,000-acre) Pyramid Fields of the Memphis and its Necropolis UNESCO World Heritage Site, inscribed in 1979.[1] The pyramid fields include the Abusir, Saqqara, and Dahshur pyramid complexes, that were all built in the vicinity of Egypt's ancient capital of Memphis.[1] Further Old Kingdom pyramid fields were located at the sites Abu Rawash, Zawyet El Aryan, and Meidum.",
    "A Moon landing or lunar landing is the arrival of a spacecraft on the surface of the Moon. This includes both crewed and robotic missions. The first human-made object to touch the Moon was the Soviet Union's Luna 2, on 13 September 1959.[3] The United States' Apollo 11 was the first crewed mission to land on the Moon, on 20 July 1969.[4] There were six crewed U.S. landings between 1969 and 1972, and numerous uncrewed landings, with no soft landings happening between 22 August 1976 and 14 December 2013. The United States is the only country to have successfully conducted crewed missions to the Moon, with the last departing the lunar surface in December 1972. All soft landings took place on the near side of the Moon until 3 January 2019, when the Chinese Chang'e 4 spacecraft made the first landing on the far side of the Moon.[5]",
    "Proteins are large biomolecules and macromolecules that comprise one or more long chains of amino acid residues. Proteins perform a vast array of functions within organisms, including catalysing metabolic reactions, DNA replication, responding to stimuli, providing structure to cells and organisms, and transporting molecules from one location to another. Proteins differ from one another primarily in their sequence of amino acids, which is dictated by the nucleotide sequence of their genes, and which usually results in protein folding into a specific 3D structure that determines its activity. A linear chain of amino acid residues is called a polypeptide. A protein contains at least one long polypeptide. Short polypeptides, containing less than 20-30 residues, are rarely considered to be proteins and are commonly called peptides. The individual amino acid residues are bonded together by peptide bonds and adjacent amino acid residues. The sequence of amino acid residues in a protein is defined by the sequence of a gene, which is encoded in the genetic code. In general, the genetic code specifies 20 standard amino acids; but in certain organisms the genetic code can include selenocysteine and—in certain archaea—pyrrolysine. Shortly after or even during synthesis, the residues in a protein are often chemically modified by post-translational modification, which alters the physical and chemical properties, folding, stability, activity, and ultimately, the function of the proteins. Some proteins have non-peptide groups attached, which can be called prosthetic groups or cofactors. Proteins can also work together to achieve a particular function, and they often associate to form stable protein complexes.",
  ];

  // Create a custom command to perform the sentiment analysis test
  Cypress.Commands.add("performSentimentAnalysisTest", (text) => {
    cy.visit("/");
    cy.viewport(1536, 960);

    // Type the paragraph into the textarea
    cy.get("#inputted-text").type(text);

    cy.get("#sentiment-result", { timeout: 10000 }).then(($span) => {
      // Store the initial value of the span
      const initialValue = $span.text();

      // Click the Sentiment button
      cy.get("button").contains("Sentiment").click();

      // Use the .should() method to check if the value has changed
      cy.get("#sentiment-result").should(($updatedSpan) => {
        const updatedValue = $updatedSpan.text();
        expect(updatedValue).not.to.equal(initialValue);
      });
    });
  });

  // Iterate through the randomParagraphs and run the test for each one
  randomParagraphs.forEach((text, index) => {
    it(`should analyze paragraph ${index + 1} sentiment`, () => {
      cy.performSentimentAnalysisTest(text);
    });
  });
});
