name: Run Cypress Tests

on:
    pull_request:
      branches: [ "development", "staging", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Resolve dependency error
        working-directory: ./client
        run: npm config set legacy-peer-deps true

      - name: Install dependencies
        run: npm install
        working-directory: ./client
    
      - name: Install dev dependencies
        run: npm install --peer
      
      - name: Install server dependencies
        run: pip install -r server/requirements.txt

      - name: Start a server for frontend and backend
        run: |
          npm run dev &
          echo $! > both_server_pid.txt

      - name: Wait for the server to start
        run: |
          while ! curl -s http://localhost:3000 ; do
            sleep 1
          done

      - name: Wait for the backend server to start
        run: |
          while ! curl -s http://localhost:8000/api ; do
            sleep 1
          done

      - name: Run Cypress tests
        run: npx cypress run --headless

      - name: Stop the server
        run: kill $(cat both_server_pid.txt)