name: Python Backend CI

on:
  pull_request:
    branches: [ "development", "staging", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./server

    - name: Run server syntax test
      run: |
        python -m py_compile ./src/main.py
      working-directory: ./server

    - name: Run tests
      run: |
        python -m unittest discover -p '*_test.py'
      working-directory: ./server







